export const ADD_PIN_CHAT_LOADING = "ADD_PIN_CHAT_LOADING";
export const ADD_PIN_CHAT_SUCCESS = "ADD_PIN_CHAT_SUCCESS";
export const ADD_PIN_CHAT_ERROR = "ADD_PIN_CHAT_ERROR";

export const GET_PIN_CHATS_LOADING = "GET_PIN_CHATS_LOADING";
export const GET_PIN_CHATS_SUCCESS = "GET_PIN_CHATS_SUCCESS";
export const GET_PIN_CHATS_ERROR = "GET_PIN_CHATS_ERROR";

export const DELETE_PIN_CHAT_SUCCESS = "DELETE_PIN_CHAT_SUCCESS";
